#Minecraft server properties
#Sun Jun 24 21:46:38 ICT 2018
generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=true
prevent-proxy-connections=false
server-port=12345
max-world-size=29999984
level-type=FLAT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=25.66.54.212
network-compression-threshold=256
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
hardcore=false
snooper-enabled=true
resource-pack-sha1=
online-mode=false
resource-pack=
pvp=true
difficulty=1
enable-command-block=true
gamemode=1
player-idle-timeout=0
max-players=10
max-tick-time=60000
spawn-monsters=true
view-distance=10
generate-structures=true
motd=Hello Yourscraftvietnam \!
